# Change these first
owner: joahn3 # Your GitHub organization or username, where this repository lives
repo: upptime2 # The name of this repository
user-agent: joahn3

sites:
  - name: firaCODE.ro
    url: https://firacode.ro
    icon: 
  - name: firaWEB.ro
    url: https://firaweb.ro
    icon: 
  - name: TemeJoc.ro
    url: https://temejoc.ro
    icon: https://temejoc.ro/wp-content/uploads/2025/12/cropped-temejoc-logo-simplu-fundal-transparent-v3-xp-orbit-192x192.avif
  - name: ChicRoumaine.com
    url: https://www.chicroumaine.com
    icon: https://chicroumaine.com/wp-content/uploads/2016/12/logo_chicroumaine.png
  - name: Tsty
    url: https://tsty.ro
  - name: GoodPC.ro
    url: https://goodpc.ro
    icon: https://goodpc.ro/assets/images/goodpc-logo.svg
  - name: Notariat Sector 4
    url: https://notarsector4.ro
  - name: Notariat Sector 4 <Google version>
    url: https://sites.google.com/view/notariatonline-ro
  - name: Zametu
    url: https://zametu.ro
  - name: consilierJuridicOnline.ro
    url: https://consilierjuridiconline.ro
    icon: https://consilierjuridiconline.ro/content/images/size/w600/2022/02/logo-consilier_juridic-removebg-preview.png
  - name: Parental Control Romania
    url: https://parentalcontrol.ro
  - name: WeSecureWeb.dev
    url: https://wesecureweb.dev
  - name: Restaurant La Sulea
    url: https://la-sulea.business.site
  - name: Profesor Floriana Pliundra
    url: https://floriana-pliundra-website.vercel.app
  - name: ionutFrancisc.com (Netlify Dev version)
    url: https://ionut-francisc.netlify.app
    icon: https://ionut-francisc.netlify.app/favicon.png
  - name: BOLDmodels.ro
    url: https://boldmodels.ro
    icon: https://www.boldmodels.ro/wp-content/uploads/2025/12/bold-models-school-logo-33.png
  - name: Security & Telecom Systems
    url: https://security-telecom.ro
    icon: https://security-telecom.ro/wp-content/uploads/2023/01/logo-security-telecom-removebg-preview.png
  - name: new | Security & Telecom Systems
    url: https://security-telecom.netlify.app
    icon: https://security-telecom.ro/wp-content/uploads/2023/01/logo-security-telecom-removebg-preview.png
  - name: BaffiCafe.ro
    url: https://bafficafe.ro
    icon: https://bafficafe.ro/wp-content/uploads/2021/03/cropped-cropped-Logo-Baffi-Cafe-2-300x113.png
  - name: Firacode clients uptime monitoring
    url: https://joahn3.github.io/upptime2/
    icon: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  - name: earthlink uptime monitoring
    url: https://joahn3.github.io/earthlink-uptime/
    icon: https://earthlink.ro/favico.png

status-website:
  theme: dark
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime2
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Firacode SRL > Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page."
  # introMessage: This is a status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages.
  navbar:

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
