# Change these first
owner: joahn3 # Your GitHub organization or username, where this repository lives
repo: upptime2 # The name of this repository
user-agent: joahn3

sites:
  - name: Firacode.ro
    url: https://firacode.ro
    icon: 
  - name: Chic Roumaine
    url: https://www.chicroumaine.com
  - name: Earthlink
    url: https://earthlink.ro
  - name: Tsty
    url: https://tsty.ro
  - name: GoodPC
    url: https://goodpc.ro
  - name: GoodPC <Google version>
    url: https://good-pc.business.site
  - name: Ioana Hutter - Contabil Sector 3 <Google version>
    url: https://expert-contabil-sector3.business.site/
    icon: https://expert-contabil-sector3.business.site/
  - name: Expert contabil Sector 3 website
    url: https://sites.google.com/view/expert-contabil-sector3/
    icon: https://sites.google.com/view/expert-contabil-sector3/
  - name: RolCris.ro
    url: https://rolcris.ro
  - name: Notariat Sector 4
    url: https://notarsector4.ro
  - name: Notariat Sector 4 <Google version>
    url: https://sites.google.com/view/notariatonline-ro
  - name: Zametu
    url: https://zametu.ro
  - name: consilierJuridicOnline.ro
    url: https://consilierjuridiconline.ro
    icon: https://consilierjuridiconline.ro/content/images/size/w600/2022/02/logo-consilier_juridic-removebg-preview.png
  - name: Parental Control Romania
    url: https://parentalcontrol.ro
  - name: WeSecureWeb.dev
    url: https://wesecureweb.dev
  - name: Restaurant La Sulea
    url: https://la-sulea.business.site
  - name: Profesor Floriana Pliundra
    url: https://floriana-pliundra-website.vercel.app
  - name: ionutFrancisc.com (Netlify Dev version)
    url: https://ionut-francisc.netlify.app
    icon: https://ionut-francisc.netlify.app/favicon.png
  - name: Firacode clients uptime monitoring
    url: https://joahn3.github.io/upptime2/
    icon: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  - name: Ledone.ro
    url: https://ledone.ro/
    icon: https://www.ledone.ro/img/led-one-logo-1545331888.jpg
  - name: BOLD Models
    url: https://cursmodeling.ro
    icon: https://www.cursmodeling.ro/wp-content/uploads/2022/07/curs-modeling-bold-models-school-logo.jpg
  - name: Security & Telecom Systems
    url: https://security-telecom.ro
  - name: Baffi Cafe
    url: https://bafficafe.ro
    icon: https://bafficafe.ro/wp-content/uploads/2021/03/cropped-cropped-Logo-Baffi-Cafe-2-300x113.png
  - name: Baffi Cafe <Google version>
    url: https://restaurant-baffi-cafe-bragadiru.business.site/
    icon: https://bafficafe.ro/wp-content/uploads/2021/03/cropped-cropped-Logo-Baffi-Cafe-2-300x113.png


status-website:
  theme: dark
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime2
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Firacode SRL > Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page."
  # introMessage: This is a status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages.
  navbar:

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
