# Change these first
owner: joahn3 # Your GitHub organization or username, where this repository lives
repo: upptime2 # The name of this repository
user-agent: joahn3

sites:
  - name: Chic Roumaine
    url: https://www.chicroumaine.com
  - name: Earthlink
    url: https://earthlink.ro
  - name: Tsty
    url: https://tsty.ro
  - name: GoodPC
    url: https://goodpc.ro
  - name: GoodPC <Google version>
    url: https://good-pc.business.site
  - name: Anahicont
    url: https://anahicont.ro
  - name: RolCris.ro
    url: https://rolcris.ro
  - name: Notariat Sector 4
    url: https://notarsector4.ro
  - name: Notariat Sector 4 <Google version>
    url: https://sites.google.com/view/notariatonline-ro
  - name: Zametu
    url: https://zametu.ro
  - name: Parental Control Romania
    url: https://parentalcontrol.ro
  - name: WeSecureWeb.dev
    url: https://wesecureweb.dev
  - name: Restaurant La Sulea
    url: https://la-sulea.business.site
  - name: Profesor Floriana Pliundra
    url: https://floriana-pliundra-website.vercel.app
  

status-website:
  theme: dark
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime2
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Firacode SRL > Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page."
  # introMessage: This is a status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages.
  navbar:

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
